### ISSUE TITLE
Difficulty differences

### ISSUE THREAD

**Issue by Gardenette** [untamed-team/project-untamed#356]
Need a screen that outlines the differences in difficulty settings when you are picking a difficulty

**Comment by stygmaskyzoo** [comment]
what are the differences at the moment?

**Comment by LowEffortCoding** [comment]
hard mode has different teams for trainers, has a hard cap on EXP (disallowing overleveling) and fully blocks the player from using the bag if the battle is a trainer battle
normal mode has easier teams for trainers, has a soft cap on EXP (allowing overleveling) and only blocks out the bag if the battle is a trainer battle and once the player used 3 healing items

**Comment by Gardenette** [comment]
@LowEffortCoding why would you restrict anything in normal mode? I don't get it
I don't think the bag should be restricted in normal mode

**Comment by LowEffortCoding** [comment]
as the AI will never ever use items since I forced her to never do that, it would be unfair for the player to do the "infinity full restore" trick that everyone hates (seriously people only remember the gen2 champion for his 3 dragonites and that he spams full restores like no tomorrow), it slows down the battle and doesn't create new strategies, but I won't ban it outright for the casuals as I understand they need the training wells

I tested it on my other project for a very good to neutral feedback from the casuals, essentially it went from "oh cool now it's more of a spare resource" to "I only used 1 or 2 items anyway lol"

**Comment by Gardenette** [comment]
Heard. There are some people who just want to breeze through the battles though. And I think we should allow the normal mode players to do anything they would be able to do in an official game

**Comment by Gardenette** [comment]
We need to decide on this. I guess in the meeting tomorrow

**Comment by ChespinCraft** [comment]
I'm still against the bag being restricted in normal mode altogether but the cap should at least be upped to 5 instead of 3. We decided to implement difficulty changes into tips for the demo so that is done, but ill leave this issue open until the cap is increased (or destroyed :sorbthonk:)

**Comment by stygmaskyzoo** [comment]
i think we can go up to 5 for demo and see the feedback

**Comment by LowEffortCoding** [comment]
i prefer keeping it down at 3, its a okay number of items that have been tested before, if newbies dont like it increase it steadly instead of jumping the shark

**Comment by Gardenette** [comment]
added
