### ISSUE TITLE
consider replacing the pumpkaboo quest

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#494]
most feedback seems negative about the "grind" it implies

**Comment by Gardenette** [comment]
I think the problem is all those people were expecting to finish that Quest all in one sitting for some reason. We don't need to make all the quests so short or easy that you complete them all in one play session. I do think we need to give the player a better reward though. Right now it is a phantump and mulch

I don't have a problem with getting rid of the pumpkaboo quest if we replace it with a better one. But I don't want to get rid of a quest just because some people don't like that you can't complete it quickly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: stygma ***@***.***>
Sent: Tuesday, February 21, 2023 6:52:27 PM
To: untamed-team/project-untamed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [untamed-team/project-untamed] consider replacing the pumpkaboo quest (Issue #494)


most feedback seems negative about the "grind" it implies

**Comment by Gardenette** [comment]
Oh actually I know why people hate it so much. It's because they can't get Phantump and Trevenant to complete the demo dex until they complete that quest

**Comment by stygmaskyzoo** [comment]
yeah that's it
no issue for future demos tho

**Comment by Gardenette** [comment]
Yeah because I think phantump would be obtainable elsewhere. Maybe this phantump could be special somehow though

**Comment by Gardenette** [comment]
Not sure what to do with this. I guess we make the reward better? Or give a reward for each pumpkaboo shown?

**Comment by stygmaskyzoo** [comment]
i think this is fine as it is for the moment
