### ISSUE TITLE
credits have to be shorter or something

### ISSUE THREAD

**Issue by stygmaskyzoo** [untamed-team/project-untamed#497]
or something

**Comment by Gardenette** [comment]
We could just make them skippable. Currently they are only skippable if you have seen them before. But we can make them skippable even if it is your first time seeing them. I don't want to shorten them because I don't want to take people out, but I also don't want to make them faster because some people might actually want to see their names in the credits and might miss it if it is going too fast. Also some people like reading all the different people's names in credits

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: stygma ***@***.***>
Sent: Tuesday, February 21, 2023 7:14:20 PM
To: untamed-team/project-untamed ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [untamed-team/project-untamed] credits have to be shorter or something (Issue #497)


or something

**Comment by stygmaskyzoo** [comment]
can we make skip appear when you have been 5-10 secs into the credits? 
with a note on a corner with the button you have to press

**Comment by Gardenette** [comment]
yes
