### ISSUE TITLE
Status and RNG rework

### ISSUE THREAD

**Issue by LowEffortCoding** [untamed-team/project-untamed#552]
confusion
- psychic types are immune
- remove it's % of hitting itself and replace it with ability nullification 
- cannot stack with other statuses, in other words remove it's volatile status 
- create new icons for it

paralysis
- remove the % of not moving this turn
- (?) affecting priority? not having any effect other than speed crippling?

infatuation
- remove it

leech seed
- (?) make ice and bug types immune to it?
- have a hard CAP on how much damage it does (avoiding boss pokemon cheesing)

curse
- (?) remove the ghost-type special effect

**Comment by stygmaskyzoo** [comment]
- confusion: add that a lot less mons will get it

- paralysis: i feel like it has to do something more than the speed crip, maybe it can do the immobilize thing but on alternate turns, so its not random and you can play around it

- infatuation fine

- i dont like leech seed immunity just because it doesnt make sense from a physical perspective, if that makes sense, but some other change could be fine

- why curse?
